 
package plugins

// this file is automatically generated

import (
  "github.com/pkg/errors"
	"github.com/bytesparadise/libasciidoc/pkg/types"

  log "github.com/sirupsen/logrus"
)

func wrapInlineImage(obj *types.InlineImage) Wrap {
  log.Trace("Wrapping a InlineImage")

  // add type
  wrapped := Wrap {
    Type: "InlineImage",
    Value: nil,
  }

  // return nil values
  if obj == nil {
    return wrapped
  }

  // wrap non-atomic parts and store atoms
  wrapped.Value = map[string]interface{}{
  
    "location": wrap(obj.Location),
  
    "attributes": wrap(obj.Attributes),
  
  }

  return wrapped
}

func unwrapInlineImage(value interface{}) (*types.InlineImage, error) {
  log.Trace("Unwrapping a InlineImage")

  // if it's nil, just return a nil of its type
  if value == nil {
    log.Trace("InlineImage is nil")
    return (*types.InlineImage)(nil), nil
  }

  // make sure all parts are present
  objMap, ok := value.(map[string]interface{})
  if ! ok {
    return nil, errors.New("'InlineImage' type not map[string]interface{}")
  }
  
    location, ok := objMap["location"]
    if ! ok {
      return nil, errors.New("InlineImage does not contain 'location'")
    }
  
    attributes, ok := objMap["attributes"]
    if ! ok {
      return nil, errors.New("InlineImage does not contain 'attributes'")
    }
  

  // unwrap non-atomic parts
  var err error
  
    
      log.Trace("Unwrapping InlineImage location")
      location, err = unwrap(location)
      if err != nil {
        return nil, err
      }
    
  
    
      log.Trace("Unwrapping InlineImage attributes")
      attributes, err = unwrap(attributes)
      if err != nil {
        return nil, err
      }
    
  

  // assert the types of the parts
  
    
      assertedLocation, ok := location.(*types.Location)
      if ! ok {
        return nil, errors.New("InlineImage Location is not type *types.Location")
      }
    
  
    
      assertedAttributes, ok := attributes.(types.Attributes)
      if ! ok {
        return nil, errors.New("InlineImage Attributes is not type types.Attributes")
      }
    
  

  // build object
  return &types.InlineImage{
    Location: assertedLocation,
    Attributes: assertedAttributes,
  }, nil
}
