= Plugins

This implements a simple system for building plugins for libasciidoc.
Plugins inject themselves in the flow of the `Convert` function:

[plantuml, target=plugin, format=svg]
....
@startuml
ditaa
+------------+
| PreProcess |
+------------+
      |
      V
+------------+
|   Parse    |
+------------+
      |
      V
+------------+
|  Validate  |
+------------+
      |               +-----------+
      +-------------->|           |
                      | PreRender |
      +---------------|  Plugins  |
      |               |           |
      V               +-----------+
+------------+
|   Render   |
+------------+
@enduml
....

== Using Plugins

Plugins can be enabled via the commandline with the `-p` option:

[source, console]
----
$ ./bin/libasciidoc -p test/plugins/pass README.adoc
----

You can use the `-p` option multiple times to include multiple plugins.

== Creating Plugins

libasciidoc plugins are executables that recieve a JSON version of the `Document` on stdin and write their manipulated version of the `Document` on stdout.
Any errors can be written to stderr and will halt the conversion process.
The `plugins.MarshalJSON` and `plugins.UnmarshalJSON` functions are exported to make things easier for golang plugins, but in theory a plugin could be written in any language.
Here is an example of a basic, passthough function in a plugin:

[source, golang]
----
package main

import (
  "os"
  "io"
  "fmt"

	"github.com/bytesparadise/libasciidoc/pkg/plugins"
)

func main() {
  bytes, err := io.ReadAll(os.Stdin)
  if err != nil {
    fmt.Fprintf(os.Stderr, "Error reading Stdin: %s", err)
    return
  }
  doc, err := plugins.UnmarshalJSON(bytes)
  if err != nil {
    fmt.Fprintf(os.Stderr, "Error converting JSON to doc: %s", err)
    return
  }

  // YOUR CODE HERE!

  json, err := plugins.MarshalJSON(doc)
  if err != nil {
    fmt.Fprintf(os.Stderr, "Error converting doc to JSON: %s", err)
    return
  }
  _, err = os.Stdout.Write(json)
  if err != nil {
    fmt.Fprintf(os.Stderr, "Error writing to Stdout: %s", err)
  }
  return
}
----

This will allow you to modify the `Document` before it is rendered in `libasciidoc.go`.
For a more complete example of a plugin, see https://github.com/rxt1077/libasciidoc-diagram[libasciidoc-diagram].
